### ISSUE TITLE
Certificate validation can use the wrong certificate if a server hosts multiple domains

### ISSUE THREAD

**Issue by ric2b** [nullbleed/fancy-motd#1]
First of all, thanks for making this, it's really nice! :D

I was having an issue with the certificate validation, it turns out that if there are multiple sites on the same IP you need to add `-servername "$domain"` ([SO answer](https://stackoverflow.com/a/24615393)) to the openssl call that fetches the certificate, here:
https://github.com/nullbleed/fancy-motd/blob/master/modules/ssl.bash#L28

The change is minimal so there's no point in issuing a pull request, the diff is basically this:
```
-- openssl s_client -connect "$domain:443" < /dev/null 2>/dev/null \
++ openssl s_client -connect "$domain:443" -servername "$domain" < /dev/null 2>/dev/null \
```

**Comment by dj95** [comment]
I'm happy that you like the script!

Thanks for your advice in the openssl module! I've added it in commit  https://github.com/nullbleed/fancy-motd/commit/d45c1a90bc801df3cb2cb245affa58455be2e5fb .
